apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-api
  namespace: banking
spec:
  replicas: 2
  selector:
    matchLabels: { app: accounts-api }
  template:
    metadata:
      labels: { app: accounts-api }
    spec:
      containers:
        - name: accounts-api
          image: <acr>.azurecr.io/banking-domain-accounts-api:latest
          ports:
            - { name: rest, containerPort: 8080 }
            - { name: grpc, containerPort: 8090 }
          envFrom:
            - configMapRef: { name: banking-config }
            - secretRef: { name: banking-secrets }
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests: { cpu: "100m", memory: "192Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-svc
  namespace: banking
spec:
  type: ClusterIP        # nội bộ — REST + gRPC (8090) cho Payments gọi
  selector: { app: accounts-api }
  ports:
    - { name: rest, port: 8080, targetPort: 8080 }
    - { name: grpc, port: 8090, targetPort: 8090 }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: accounts-api-hpa
  namespace: banking
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: accounts-api }
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
